# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kfc.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 815)
        MainWindow.setMinimumSize(QtCore.QSize(707, 815))
        MainWindow.setMaximumSize(QtCore.QSize(707, 815))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(707, 815))
        self.centralwidget.setMaximumSize(QtCore.QSize(707, 815))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 711, 815))
        self.tabWidget.setMinimumSize(QtCore.QSize(711, 815))
        self.tabWidget.setMaximumSize(QtCore.QSize(711, 815))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(711, 815))
        self.tab.setMaximumSize(QtCore.QSize(711, 815))
        self.tab.setObjectName("tab")
        self.gridWidget = QtWidgets.QWidget(self.tab)
        self.gridWidget.setEnabled(True)
        self.gridWidget.setGeometry(QtCore.QRect(0, 0, 711, 815))
        self.gridWidget.setMinimumSize(QtCore.QSize(711, 815))
        self.gridWidget.setMaximumSize(QtCore.QSize(711, 815))
        self.gridWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.gridWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 40)
        self.gridLayout.setObjectName("gridLayout")
        self.spin_5 = QtWidgets.QSpinBox(self.gridWidget)
        self.spin_5.setEnabled(False)
        self.spin_5.setMinimumSize(QtCore.QSize(100, 20))
        self.spin_5.setMaximumSize(QtCore.QSize(100, 20))
        self.spin_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spin_5.setSuffix("")
        self.spin_5.setMinimum(1)
        self.spin_5.setObjectName("spin_5")
        self.gridLayout.addWidget(self.spin_5, 4, 3, 1, 1)
        self.spin_6 = QtWidgets.QSpinBox(self.gridWidget)
        self.spin_6.setEnabled(False)
        self.spin_6.setMinimumSize(QtCore.QSize(100, 20))
        self.spin_6.setMaximumSize(QtCore.QSize(100, 20))
        self.spin_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spin_6.setSuffix("")
        self.spin_6.setMinimum(1)
        self.spin_6.setObjectName("spin_6")
        self.gridLayout.addWidget(self.spin_6, 5, 3, 1, 1)
        self.spin_1 = QtWidgets.QSpinBox(self.gridWidget)
        self.spin_1.setEnabled(False)
        self.spin_1.setMinimumSize(QtCore.QSize(100, 20))
        self.spin_1.setMaximumSize(QtCore.QSize(100, 20))
        self.spin_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spin_1.setFrame(True)
        self.spin_1.setReadOnly(False)
        self.spin_1.setAccelerated(False)
        self.spin_1.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.spin_1.setKeyboardTracking(True)
        self.spin_1.setSuffix("")
        self.spin_1.setMinimum(1)
        self.spin_1.setDisplayIntegerBase(10)
        self.spin_1.setObjectName("spin_1")
        self.gridLayout.addWidget(self.spin_1, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("chizburger-s-lukom.png"))
        self.label.setScaledContents(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.check_1 = QtWidgets.QCheckBox(self.gridWidget)
        self.check_1.setMinimumSize(QtCore.QSize(20, 20))
        self.check_1.setMaximumSize(QtCore.QSize(20, 20))
        self.check_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_1.setText("")
        self.check_1.setCheckable(True)
        self.check_1.setChecked(False)
        self.check_1.setObjectName("check_1")
        self.gridLayout.addWidget(self.check_1, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 100))
        self.label_2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("boksmaster-ostryy.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridWidget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 100))
        self.label_3.setMaximumSize(QtCore.QSize(100, 100))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("12.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.spin_2 = QtWidgets.QSpinBox(self.gridWidget)
        self.spin_2.setEnabled(False)
        self.spin_2.setMinimumSize(QtCore.QSize(100, 20))
        self.spin_2.setMaximumSize(QtCore.QSize(100, 20))
        self.spin_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spin_2.setSuffix("")
        self.spin_2.setMinimum(1)
        self.spin_2.setObjectName("spin_2")
        self.gridLayout.addWidget(self.spin_2, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridWidget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 100))
        self.label_4.setMaximumSize(QtCore.QSize(100, 100))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("23.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridWidget)
        self.label_6.setMinimumSize(QtCore.QSize(100, 100))
        self.label_6.setMaximumSize(QtCore.QSize(100, 100))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("tvister-original-nyy.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.check_2 = QtWidgets.QCheckBox(self.gridWidget)
        self.check_2.setMinimumSize(QtCore.QSize(20, 20))
        self.check_2.setMaximumSize(QtCore.QSize(20, 20))
        self.check_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_2.setObjectName("check_2")
        self.gridLayout.addWidget(self.check_2, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridWidget)
        self.label_5.setMinimumSize(QtCore.QSize(100, 100))
        self.label_5.setMaximumSize(QtCore.QSize(100, 100))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("21.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.spin_3 = QtWidgets.QSpinBox(self.gridWidget)
        self.spin_3.setEnabled(False)
        self.spin_3.setMinimumSize(QtCore.QSize(100, 20))
        self.spin_3.setMaximumSize(QtCore.QSize(100, 20))
        self.spin_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spin_3.setSuffix("")
        self.spin_3.setMinimum(1)
        self.spin_3.setObjectName("spin_3")
        self.gridLayout.addWidget(self.spin_3, 2, 3, 1, 1)
        self.check_4 = QtWidgets.QCheckBox(self.gridWidget)
        self.check_4.setMinimumSize(QtCore.QSize(20, 20))
        self.check_4.setMaximumSize(QtCore.QSize(20, 20))
        self.check_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_4.setObjectName("check_4")
        self.gridLayout.addWidget(self.check_4, 3, 2, 1, 1)
        self.check_5 = QtWidgets.QCheckBox(self.gridWidget)
        self.check_5.setMinimumSize(QtCore.QSize(20, 20))
        self.check_5.setMaximumSize(QtCore.QSize(20, 20))
        self.check_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_5.setObjectName("check_5")
        self.gridLayout.addWidget(self.check_5, 4, 2, 1, 1)
        self.check_3 = QtWidgets.QCheckBox(self.gridWidget)
        self.check_3.setMinimumSize(QtCore.QSize(20, 20))
        self.check_3.setMaximumSize(QtCore.QSize(20, 20))
        self.check_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_3.setObjectName("check_3")
        self.gridLayout.addWidget(self.check_3, 2, 2, 1, 1)
        self.check_6 = QtWidgets.QCheckBox(self.gridWidget)
        self.check_6.setMinimumSize(QtCore.QSize(20, 20))
        self.check_6.setMaximumSize(QtCore.QSize(20, 20))
        self.check_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_6.setObjectName("check_6")
        self.gridLayout.addWidget(self.check_6, 5, 2, 1, 1)
        self.spin_4 = QtWidgets.QSpinBox(self.gridWidget)
        self.spin_4.setEnabled(False)
        self.spin_4.setMinimumSize(QtCore.QSize(100, 20))
        self.spin_4.setMaximumSize(QtCore.QSize(100, 20))
        self.spin_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spin_4.setSuffix("")
        self.spin_4.setMinimum(1)
        self.spin_4.setObjectName("spin_4")
        self.gridLayout.addWidget(self.spin_4, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridWidget)
        self.label_7.setMinimumSize(QtCore.QSize(200, 100))
        self.label_7.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridWidget)
        self.label_8.setMinimumSize(QtCore.QSize(200, 100))
        self.label_8.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridWidget)
        self.label_9.setMinimumSize(QtCore.QSize(200, 100))
        self.label_9.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridWidget)
        self.label_10.setMinimumSize(QtCore.QSize(200, 100))
        self.label_10.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridWidget)
        self.label_11.setMinimumSize(QtCore.QSize(200, 100))
        self.label_11.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridWidget)
        self.label_12.setMinimumSize(QtCore.QSize(200, 100))
        self.label_12.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.print = QtWidgets.QPlainTextEdit(self.tab_2)
        self.print.setEnabled(True)
        self.print.setGeometry(QtCore.QRect(0, 0, 711, 815))
        self.print.setMinimumSize(QtCore.QSize(711, 815))
        self.print.setMaximumSize(QtCore.QSize(711, 815))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.print.setFont(font)
        self.print.setFocusPolicy(QtCore.Qt.NoFocus)
        self.print.setStyleSheet("border: none;")
        self.print.setReadOnly(True)
        self.print.setPlainText("")
        self.print.setCenterOnScroll(False)
        self.print.setObjectName("print")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KFC"))
        self.check_2.setText(_translate("MainWindow", "CheckBox"))
        self.check_4.setText(_translate("MainWindow", "CheckBox"))
        self.check_5.setText(_translate("MainWindow", "CheckBox"))
        self.check_3.setText(_translate("MainWindow", "CheckBox"))
        self.check_6.setText(_translate("MainWindow", "CheckBox"))
        self.label_7.setText(_translate("MainWindow", "Чизбургер с луком\n"
"74 рубля"))
        self.label_8.setText(_translate("MainWindow", "Шефбургер Джуниор\n"
"109 рублей"))
        self.label_9.setText(_translate("MainWindow", "Баскет L\n"
"709 рублей"))
        self.label_10.setText(_translate("MainWindow", "Баскет 5 ножек\n"
"384 рубля"))
        self.label_11.setText(_translate("MainWindow", "Твистер оригинальный\n"
"174 рубля"))
        self.label_12.setText(_translate("MainWindow", "Боксмастер\n"
"214 рублей"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Меню"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Корзина"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
